In [24]:
import pandas as pd
import sqlite3
import numpy as np

connection = sqlite3.connect('D:/Akademik/Semester 7/TA 1/Example 1/airport-develop/airport-develop/resources/database/Airports.db')
query = 'select * from runways'
database = pd.read_sql_query(query, connection)

icao_code_list = database["airportICAO"].unique()
icao_code_list

OAData = pd.read_csv('D:\Akademik\BachelorArbeit\Data\OArunways.csv')

In [25]:
OAData

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
0,269408,6523,00A,80.0,80.0,ASPH-G,1,0,H1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,255155,6524,00AK,2500.0,70.0,GRVL,0,0,N,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN,NaN,NaN,NaN
2,254165,6525,00AL,2300.0,200.0,TURF,0,0,01,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN
3,270932,6526,00AR,40.0,40.0,GRASS,0,0,H1,NaN,NaN,NaN,NaN,NaN,H1,NaN,NaN,NaN,NaN,NaN
4,322128,322127,00AS,1450.0,60.0,Turf,0,0,1,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43888,235186,27243,ZYTX,10499.0,148.0,CON,1,0,06,41.630402,123.469002,171.0,49.0,NaN,24,41.649300,123.498001,197.0,229.0,NaN
43889,235169,27244,ZYYJ,8530.0,148.0,CON,1,0,09,42.881100,129.436005,623.0,81.7,NaN,27,42.884499,129.466995,597.0,261.7,NaN
43890,354997,317861,ZYYK,8202.0,NaN,NaN,0,0,04,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,NaN
43891,346789,346788,ZZ-0003,1800.0,15.0,Turf,0,0,15,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN,NaN,NaN
43892,313663,313629,ZZZZ,1713.0,82.0,concrete,0,0,18,30.783501,130.272995,NaN,NaN,NaN,36,30.778099,130.272995,NaN,NaN,NaN

In [26]:
OAData.loc[(OAData["airport_ident"] =="KMGW")]

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
23153,243373,3682,KMGW,2769.0,75.0,ASP,1,0,05,39.638901,-79.917503,1241.0,44.9,NaN,23,39.644299,-79.910500,1241.0,224.9,NaN
23154,243374,3682,KMGW,5199.0,150.0,ASP,1,0,18,39.650700,-79.918800,1236.0,172.4,NaN,36,39.636501,-79.916298,1244.0,352.4,NaN
23155,355024,3682,KMGW,2769.0,75.0,ASP,0,1,5,NaN,NaN,NaN,45.0,NaN,23,NaN,NaN,NaN,225.0,NaN

In [27]:
OAData.loc[(OAData["airport_ident"] =="SBBE")]

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
32346,324528,5867,SBBE,6004.0,148.0,ASP,0,0,02,-1.39055,-48.47715,27.0,5.0,NaN,20,-1.374064,-48.475746,54.0,185.0,NaN
32347,233992,5867,SBBE,9186.0,148.0,ASP,0,0,6,NaN,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN
32348,233991,5867,SBBE,108.0,108.0,CON,0,0,7,NaN,NaN,NaN,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN

In [28]:
OAData.drop([23155], axis=0, inplace=True)
OAData.drop([32348], axis=0, inplace=True)

In [29]:
OAData.loc[(OAData["airport_ident"] =="KMGW")]

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
23153,243373,3682,KMGW,2769.0,75.0,ASP,1,0,05,39.638901,-79.917503,1241.0,44.9,NaN,23,39.644299,-79.910500,1241.0,224.9,NaN
23154,243374,3682,KMGW,5199.0,150.0,ASP,1,0,18,39.650700,-79.918800,1236.0,172.4,NaN,36,39.636501,-79.916298,1244.0,352.4,NaN

In [30]:
OAData.loc[(OAData["airport_ident"] =="SBBE")]

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
32346,324528,5867,SBBE,6004.0,148.0,ASP,0,0,02,-1.39055,-48.47715,27.0,5.0,NaN,20,-1.374064,-48.475746,54.0,185.0,NaN
32347,233992,5867,SBBE,9186.0,148.0,ASP,0,0,6,NaN,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN

In [31]:
database

,airportICAO,rwyIdent,rwyBearing,rwyTrueBearing,rwySlope,rwyThresElevation,rwyThresCrossHeight,rwyWidth,rwyLon,rwyLat,...,gldslpFreq,gldslpAngle,gldslpIdent,llzLat,llzLon,llzElevation,llzFreq,llzBearing,llzIdent,llzCategory
0,AGGH,06,59.0,68.242264,-0.221670,9.240,15.4,45.584,160.044998,-9.431740,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
1,AGGH,24,239.0,248.242264,0.221670,4.312,15.4,45.584,160.063995,-9.424260,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
2,ANYN,12,121.0,129.267903,-0.028353,6.776,15.4,45.584,166.912003,-0.542303,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
3,ANYN,30,301.0,309.267903,0.028353,6.160,15.4,45.584,166.925995,-0.553742,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
4,AYBK,04,39.0,46.780566,-0.097561,3.388,15.4,30.184,154.667999,-5.426920,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10837,OMDW,30,300.0,301.459592,NaN,170.000,NaN,60.000,55.180199,24.886000,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10838,OTBD,15,156.0,158.125868,NaN,32.000,NaN,NaN,51.556499,25.280199,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10839,OTBD,33,336.0,338.125868,NaN,25.000,NaN,NaN,51.573502,25.241899,...,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10840,UNNT,16,161.0,170.047178,-0.047750,104.000,NaN,60.000,82.594261,55.049263,...,NaN,3.0,None,NaN,NaN,NaN,NaN,NaN,None,None
10841,UNNT,34,341.0,350.047178,0.047750,101.000,NaN,60.000,82.604073,55.017220,...,NaN,3.0,None,NaN,NaN,NaN,NaN,NaN,None,None

In [32]:
database.iloc[:, 2:] = np.nan
rwy = lambda icao, ident: database.index[(database.airportICAO == icao) & (database.rwyIdent == ident)]

database

,airportICAO,rwyIdent,rwyBearing,rwyTrueBearing,rwySlope,rwyThresElevation,rwyThresCrossHeight,rwyWidth,rwyLon,rwyLat,...,gldslpFreq,gldslpAngle,gldslpIdent,llzLat,llzLon,llzElevation,llzFreq,llzBearing,llzIdent,llzCategory
0,AGGH,06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AGGH,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ANYN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANYN,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AYBK,04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10837,OMDW,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10838,OTBD,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10839,OTBD,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10840,UNNT,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10841,UNNT,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
database

data_not_found = []

import time

start = time.time()

for row in database.itertuples():
    #print("{} - {}".format(row.airportICAO, row.rwyIdent))
    
    #Ngambil data
    OAData.loc[(OAData["airport_ident"] == row.airportICAO)]
    
    #Ngambil identifier
    if (row.rwyIdent in OAData.loc[(OAData["airport_ident"] == row.airportICAO) & ((OAData["le_ident"] == row.rwyIdent) | (OAData["he_ident"] == row.rwyIdent)), "le_ident"].to_string().split(" ")):
        is_le = True
        identifier = "le_ident"
        
    elif (row.rwyIdent in OAData.loc[(OAData["airport_ident"] == row.airportICAO) & ((OAData["le_ident"] == row.rwyIdent) | (OAData["he_ident"] == row.rwyIdent)), "he_ident"].to_string().split(" ")):
        is_le = False
        identifier = "he_ident"
        
    else:
        identifier = "not_found"
        print("Data not found")
    
    #print(identifier)
    #print(row.airportICAO)
    #print(row.rwyIdent)
    
    if identifier != "not_found":
        #Ekstrak data
        if is_le:
            cursor = "le_heading_degT"
        else:
            cursor = "he_heading_degT"
            (OAData["airport_ident"] == "AYPY") & (OAData["le_ident"] == "14L")
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" "))
        try:
            rtb = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            rtb = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyTrueBearing"] = rtb

        if is_le:
            cursor = "le_elevation_ft"
        else:
            cursor = "he_elevation_ft"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            rte = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            rte = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        rte = float(rte)*0.3048
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyThresElevation"] = rte

        cursor = "width_ft"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            wft = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            wft = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        wft = float(wft)*0.3048
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyWidth"] = wft

        if is_le:
            cursor = "le_longitude_deg"
        else:
            cursor = "he_longitude_deg"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            lon = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            lon = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyLon"] = lon

        if is_le:
            cursor = "le_latitude_deg"
        else:
            cursor = "he_latitude_deg"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            lat = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            lat = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyLat"] = lat

        cursor = "length_ft"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            leng = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            leng = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        leng = float(leng)*0.3048 
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwyLength"] = leng

        cursor = "surface"
        #print(OAData.loc[(OAData["airport_ident"] == row.airportICAO), cursor].to_string().split(" "))
        try:
            sur = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[4]
        except:
            sur = OAData.loc[(OAData["airport_ident"] == row.airportICAO) & (OAData[identifier] == row.rwyIdent), cursor].to_string().split(" ")[3]
        database.loc[(database["airportICAO"] == row.airportICAO) & (database["rwyIdent"] == row.rwyIdent), "rwySurface"] = sur
    
    else:
        data_not_found.append("{}|{}".format(row.airportICAO, row.rwyIdent))
    
database
print(round(time.time()-start,3))

In [15]:
pd.set_option('display.max_columns', None)

database.tail(10)

,airportICAO,rwyIdent,rwyBearing,rwyTrueBearing,rwySlope,rwyThresElevation,rwyThresCrossHeight,rwyWidth,rwyLon,rwyLat,rwyLength,rwySurface,rwyGlideslopeAngle,ilsLat,ilsLon,ilsElevation,ilsFreq,ilsBearing,ilsIdent,ilsCategory,gldslpLat,gldslpLon,gldslpElevation,gldslpFreq,gldslpAngle,gldslpIdent,llzLat,llzLon,llzElevation,llzFreq,llzBearing,llzIdent,llzCategory
10832,OTHH,16L,156.0,156.0,NaN,3.6576,NaN,60.0456,51.608799,25.296101,4849.9776,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10833,OTHH,16R,156.0,156.0,NaN,3.6576,NaN,60.0456,51.589699,25.291,4250.1312,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10834,OTHH,34R,336.0,336.0,NaN,3.6576,NaN,60.0456,51.626801,25.2554,4849.9776,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10835,OTHH,34L,336.0,336.0,NaN,3.6576,NaN,60.0456,51.6054,25.255301,4250.1312,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10836,OMDW,12,120.0,120.0,NaN,34.7472,NaN,60.0456,55.142071,24.907091,4500.0672,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10837,OMDW,30,300.0,300.0,NaN,51.8160,NaN,60.0456,55.180138,24.88607,4500.0672,Asphalt,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10838,OTBD,15,156.0,158.2,NaN,10.6680,NaN,46.0248,51.556499,25.280199,4572.0000,ASP,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10839,OTBD,33,336.0,338.2,NaN,7.6200,NaN,46.0248,51.573502,25.241899,4572.0000,ASP,None,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
10840,UNNT,16,161.0,170.0,-0.04775,110.3376,NaN,45.1104,82.59333,55.049999,3602.1264,ASP,None,55.013248,82.605301,31.0896,NaN,NaN,None,None,55.046700,82.59726,29.8704,NaN,3.0,None,NaN,NaN,NaN,NaN,NaN,None,None
10841,UNNT,34,341.0,350.0,0.04775,112.1664,NaN,45.1104,82.603333,55.01667,3602.1264,ASP,None,55.054848,82.592537,29.8704,NaN,NaN,None,None,55.020264,82.60537,29.2608,NaN,3.0,None,NaN,NaN,NaN,NaN,NaN,None,None

In [11]:
database.to_csv('OurAirports.com.csv')

In [20]:
#import pyarrow 

#database.to_parquet('OurAirports.parquet', engine='pyarrow')

database.to_parquet('OurAirports.parquet', object_encoding='bytes', compression='gzip')

TypeError: expected list of bytes

In [24]:
compression_opts = dict(method='zip',
                        archive_name='OurAirports.csv')  
database.to_csv('OAData.zip', index=False,
          compression=compression_opts)

In [25]:
pd.read_parquet('OurAirports.parquet').head()

OSError: [Errno 22] Invalid argument

In [21]:
database.loc[(database["airportICAO"] =="PAFA")]

,airportICAO,rwyIdent,rwyBearing,rwyTrueBearing,rwySlope,rwyThresElevation,rwyThresCrossHeight,rwyWidth,rwyLon,rwyLat,rwyLength,rwySurface,rwyGlideslopeAngle,ilsLat,ilsLon,ilsElevation,ilsFreq,ilsBearing,ilsIdent,ilsCategory,gldslpLat,gldslpLon,gldslpElevation,gldslpFreq,gldslpAngle,gldslpIdent,llzLat,llzLon,llzElevation,llzFreq,llzBearing,llzIdent,llzCategory
7820,PAFA,02,10.0,38.0,0.034483,131.9784,15.400,22.86,-147.847,64.816101,883.9200,GRVL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
7821,PAFA,02L,17.0,38.0,0.025424,131.3688,17.248,45.72,-147.886002,64.802597,3596.6400,ASPH-G,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
7822,PAFA,02R,17.0,38.0,0.000000,131.9784,12.320,30.48,-147.876007,64.800201,1981.5048,ASPH-G,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
7823,PAFA,20,190.0,218.0,-0.034483,132.2832,15.400,22.86,-147.835007,64.822304,883.9200,GRVL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
7824,PAFA,20L,197.0,218.0,0.000000,131.9784,16.324,30.48,-147.850006,64.814201,1981.5048,ASPH-G,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
7825,PAFA,20R,197.0,218.0,-0.025424,132.2832,17.248,45.72,-147.839005,64.828003,3596.6400,ASPH-G,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None

In [26]:
database.head(100)

,airportICAO,rwyIdent,rwyBearing,rwyTrueBearing,rwySlope,rwyThresElevation,rwyThresCrossHeight,rwyWidth,rwyLon,rwyLat,rwyLength,rwySurface,rwyGlideslopeAngle,ilsLat,ilsLon,ilsElevation,ilsFreq,ilsBearing,ilsIdent,ilsCategory,gldslpLat,gldslpLon,gldslpElevation,gldslpFreq,gldslpAngle,gldslpIdent,llzLat,llzLon,llzElevation,llzFreq,llzBearing,llzIdent,llzCategory
0,AGGH,06,59.0,68.0,-0.221670,8.5344,15.4,45.1104,160.044998,-9.43174,2200.0464,ASP,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
1,AGGH,24,239.0,248.0,0.221670,4.2672,15.4,45.1104,160.063995,-9.42426,2200.0464,ASP,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
2,ANYN,12,121.0,121.0,-0.028353,6.7056,15.4,45.1104,166.912003,-0.541181,2150.0592,ASP,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
3,ANYN,30,301.0,301.0,0.028353,6.0960,15.4,45.1104,166.925995,-0.553739,2150.0592,ASP,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
4,AYBK,04,39.0,48.0,-0.097561,3.3528,15.4,29.8704,154.667007,-5.42701,1562.1000,ASP,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,CCE4,33,325.0,301.15,-0.998800,16.0160,15.4,23.1000,-55.7825,53.4681,770.9240,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
96,CCP4,12,122.0,NaN,0.000000,102.1080,15.4,22.8600,NaN,NaN,762.0000,GRAVEL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
97,CCP4,30,302.0,NaN,0.000000,102.1080,15.4,22.8600,NaN,NaN,762.0000,GRAVEL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
98,CCZ2,12,113.0,NaN,0.000000,NaN,15.4,22.8600,NaN,NaN,762.0000,GRAVEL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None
99,CCZ2,30,293.0,NaN,0.000000,NaN,15.4,22.8600,NaN,NaN,762.0000,GRAVEL,Unknown,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,None,None

In [27]:
OArequestayah = database.head(100)

OArequestayah.to_csv('OAayah.csv')